const projects=[
["B2B Demand Generation","Lead Magnet · Landing Page · Paid Social","From insight to acquisition: building downloadable assets, landing experiences and ad creative for B2B lead generation.","public/images/b2b-ebook4-ad-01.jpg"],
["ICP Research & Tracking","Strategy · Research · Operations","A structured ICP framework that connected account research, solution mapping and campaign tracking into one operating process.","public/images/icp-process-overview.jpg"],
["AI Readiness Assessment","Interactive Campaign · Research","An assessment-led campaign designed to turn a broad AI topic into a concrete diagnostic journey and actionable report.","public/images/ai-readiness-assessment-landing.jpg"],
["ABM Email Nurture","Email · Content · Conversion","Educational email sequences that use practical resources and SEO content to create relevance before introducing the product.","public/images/abm-email-1.jpg"],
["TikTok Content System","Short-form Video · Social Growth","A repeatable short-form content approach spanning concept development, production, trend adaptation and performance learning.","public/images/tiktok-cover-trio.jpg"],
["V-Creator Program","Creator Program · Training · Analytics","Creator enablement materials, content analysis and KPI tracking designed to improve output quality and operational consistency.","public/images/v-creator-proposal.jpg"],
["Seasonal Retail Campaigns","Integrated Content · Retail","Multi-channel seasonal executions across social, website and owned channels, translating campaign themes into retail touchpoints.","public/images/seasonal-social-4.jpg"],
["Dream Christmas","Campaign Operations · Training","Customer journey, operating flow and training materials that helped turn a seasonal concept into an executable frontline experience.","public/images/dream-christmas-cover.jpg"],
["Content Workflow Automation","AI · Automation · Operations","Experiments using automated workflows to support content generation, publishing and recurring operational tasks.","public/images/make-automation-scenarios.jpg"]
];const root=document.querySelector("#projects");projects.forEach((p,i)=>{root.insertAdjacentHTML("beforeend",`<article class="project"><div><div class="meta">${String(i+1).padStart(2,"0")} · ${p[1]}</div><h3>${p[0]}</h3><p>${p[2]}</p></div><img class="project-img" loading="lazy" src="./${p[3]}" alt="${p[0]} project visual"></article>`)})